### ISSUE TITLE
Support for GitHub Enterprise?

### ISSUE THREAD

**Issue by MichaelPlank** [ANCIT/eGit-extensions#57]
Is this extension only meant for working with GitHub.com?
We are using a self hosted GitHub enterprise instance for hosting our repository and I was wondering, if the extension in general is capable of it.
In the Eclipse Preferences under git extensions, I can only input username and password, without specifying the URL to the GitHub server. This tells me, that it's only supporting GitHub.com at the moment.

I'm asking, because the "Create Pull Request" menu item is deactivated.
![screen shot 2015-10-06 at 11 56 52](https://cloud.githubusercontent.com/assets/231029/10305617/76295aa0-6c21-11e5-874b-d1c365929da0.png)

**Comment by cmalai** [comment]
Hi Michael

Thanks for using egit-extensions. You are right. At the moment Create Pull Request is for github.com but do let us know your usecase we would be more than happy to generalise it. We are using it for github and therefore didnt really think of the other usecases.

**Comment by MichaelPlank** [comment]
Hi Cmalai,
well, Github Enterprise is a self hosted Github, with the exact same functionality as Github.com.

The use case would be to add multiple Github accounts in the Eclipse preferences.
When adding an account, you can also specify the URL to the Github Enterprise server, additionally to the username and password.

When you then select "Create Pull Request" from the context menu, it will be able to create the pull request on the Github Enterprise instance.

**Comment by cmalai** [comment]
Hi Michael

Are you still interested in this Feature ? We have some bandwidth to implement this feature now.

Regards
Malai

**Comment by MichaelPlank** [comment]
Hi,
we are now using Atlassian Bitbucket in our Company, so I'm actually not interested in this feature at this time.
Thx!

**Comment by cmalai** [comment]
You would be interested in Atlassian Bitbucket Pull Request from eGitExtension. We did start on this earlier but stopped.

Would you need any feature related to Atlassian Bitbucket that we could offer do let us know ...

**Comment by luhaixun** [comment]
Hello there, 

My Employer is using GitHub Enterprise and want to check if the feature on GitHub Enterprise is already implemented or just close this ticket? From the source code, I only find BitBucketRestClient.

Thanks,
Tim
